### PR TITLE
Don't eval into the module during precompilation

### LINKED ISSUE #4: eval in __init__ breaks downstream precompilation
```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(PyMNE_doodle) pkg> st

Project PyMNE_doodle v0.1.0
Status `~/src/tmp/PyMNE_doodle/Project.toml`
  [6c5003b2] PyMNE v0.1.0


shell> cat src/PyMNE_doodle.jl

module PyMNE_doodle
using PyMNE
end


julia> using PyMNE


julia> using PyMNE_doodle

[ Info: Precompiling PyMNE_doodle [c51fb540-dcbe-4563-b378-fed5aac661c3]
ERROR: LoadError: InitError: Evaluation into the closed module `PyMNE` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `PyMNE` with `eval` during precompilation - don't do this.
Stacktrace:
 [1] eval at ./boot.jl:331 [inlined]
 [2] __init__() at /home/ubuntu/.julia/packages/PyMNE/pn9jE/src/PyMNE.jl:35
 [3] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
 [4] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:782
 [5] _require(::Base.PkgId) at ./loading.jl:1007
 [6] require(::Base.PkgId) at ./loading.jl:928
 [7] require(::Module, ::Symbol) at ./loading.jl:923
 [8] include(::Function, ::Module, ::String) at ./Base.jl:380
 [9] include(::Module, ::String) at ./Base.jl:368
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:331 [inlined]
 [12] eval(::Expr) at ./client.jl:467
 [13] top-level scope at ./none:3
during initialization of module PyMNE
in expression starting at /home/ubuntu/src/tmp/PyMNE_doodle/src/PyMNE_doodle.jl:3
ERROR: Failed to precompile PyMNE_doodle [c51fb540-dcbe-4563-b378-fed5aac661c3] to /home/ubuntu/.julia/compiled/v1.5/PyMNE_doodle/zcqTA_V5NaD.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
```

So, I have a `PyMNE_doodle` project that just depends on `PyMNE`, that contains a `module PyMNE_doodle` that just imports `PyMNE`. I get that lovely error on precompilation of `PyMNE_doodle`, even though `using PyMNE` works fine.

### PR DESCRIPTION
**Pull request by ararslan**
This avoids evaluating the symbols from MNE while Julia is precompiling. Seems to fix #4. Closes #5.

### CODE REVIEW

**Comment by ararslan** [comment]
```
$ tree
.
├── Project.toml
└── src
    └── Thingo.jl

1 directory, 2 files
$ julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-beta1 (2021-01-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(Thingo) pkg> add PyMNE#aa/precomp
     Cloning git-repo `https://github.com/beacon-biosignals/PyMNE.jl.git`
    Updating git-repo `https://github.com/beacon-biosignals/PyMNE.jl.git`
    Updating registry at `~/.julia/registries/Beacon`
    Updating git-repo `https://github.com/beacon-biosignals/BeaconRegistry.git`
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
Updating `~/Projects/test/Project.toml`
  [6c5003b2] + PyMNE v0.1.0 `https://github.com/beacon-biosignals/PyMNE.jl.git#aa/precomp`
Updating `~/Projects/test/Manifest.toml`
  [8f4d0f93] + Conda v1.5.0
  [682c06a0] + JSON v0.21.1
  [1914dd2f] + MacroTools v0.5.6
  [69de0a69] + Parsers v1.0.15
  [438e738f] + PyCall v1.92.2
  [6c5003b2] + PyMNE v0.1.0 `https://github.com/beacon-biosignals/PyMNE.jl.git#aa/precomp`
  [81def892] + VersionParsing v1.2.0
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [de0858da] + Printf
  [9a3f8284] + Random
  [9e88b42a] + Serialization
  [4ec0a83e] + Unicode
    Building PyMNE → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/c30e75022fca80ae7adfb5c1eb4a2ff85fde1554/build.log`
  Progress [========================================>]  2/2
2 dependencies successfully precompiled in 4 seconds (6 already precompiled)

julia> using Thingo

julia> Thingo.PyMNE.io.read_raw_edf
PyObject <function read_raw_edf at 0x7fcd974cfbf8>
```

File: src/PyMNE.jl [hunk 1]
```diff
@@ -28,11 +28,13 @@ function __init__()
     # all of this is __init__() so that it plays nice with precompilation
     # see https://github.com/JuliaPy/PyCall.jl/#using-pycall-from-julia-modules
     copy!(mne, pyimport("mne"))
-    # delegate everything else to mne
-    for pn in propertynames(mne)
-        isdefined(@__MODULE__, pn) && continue
-        prop = getproperty(mne, pn)
-        @eval $pn = $prop
+    if ccall(:jl_generating_output, Cint, ()) == 0
```
Comment (ericphanson) [inline src/PyMNE.jl:31]: a comment could help give context for future readers, eg
```suggestion
    # fix https://github.com/beacon-biosignals/PyMNE.jl/issues/4
    if ccall(:jl_generating_output, Cint, ()) == 0
```

**Review by palday — APPROVED** [review]
